import { useEffect, useState } from 'react'
import { useContent } from '../data/ContentContext.jsx'
const clone=x=>JSON.parse(JSON.stringify(x))
export default function DashboardPage(){
 const {content,setContent,online}=useContent();const [draft,setDraft]=useState(null),[signed,setSigned]=useState(false),[tab,setTab]=useState('Contact'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false)
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
 const data=draft||content
 async function request(method,body){const r=await fetch('/api/content',{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');return result}
 async function login(e){e.preventDefault();const password=new FormData(e.currentTarget).get('password');setBusy(true);try{await request('POST',{password});setSigned(true);if(!draft)setDraft(clone(content));setMessage('Signed in. Choose a section to edit.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 function edit(fn){setDraft(prev=>{const next=clone(prev||content);fn(next);return next});setDirty(true);setMessage('Unsaved changes')}
 async function save(){setBusy(true);try{const next=await request('PUT',data);setContent(next);setDraft(clone(next));setDirty(false);setMessage('Published. Your website now shows these updates.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const field=(label,value,onChange,extra={})=><label>{label}<input value={value} onChange={e=>onChange(e.target.value)} maxLength={500} {...extra}/></label>
 return <section className="admin-shell container"><div className="admin-heading"><div><span className="admin-eyebrow">HEXA’S / SITE MANAGER</span><h1>Your site. Up to date.</h1><p>Change the details here. Keep your students in the know.</p></div><a href="#/">View website ↗</a></div>{!online&&<p className="admin-notice">Content service is not connected. Connect Upstash Redis in Vercel to enable shared updates. Preview values are shown on the site.</p>}{!signed?<form className="admin-panel admin-login" onSubmit={login}><h2>Staff sign in</h2><p>Use the administrator password configured for this website.</p><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="button button-primary" disabled={busy||!online}>{busy?'Signing in…':'Open dashboard'}</button></form>:<><div className="admin-toolbar"><div className="filter-pills" role="group" aria-label="Dashboard sections">{['Contact','Courses','Club schedules','Mock & partial'].map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><button className="link-button" disabled={busy} onClick={async()=>{try{await request('DELETE');setSigned(false);setMessage('Signed out.')}catch(e){setMessage(e.message)}}}>Sign out</button></div><form onSubmit={e=>{e.preventDefault();save()}}>
 {tab==='Contact'&&<div className="admin-panel"><h2>Contact details</h2><p>This number is used for admissions calls and WhatsApp. Registration calls and WhatsApp use +8801334934850.</p><div className="admin-fields">{field('Admissions phone',data.phone,v=>edit(d=>d.phone=v),{required:true,type:'tel',maxLength:30})}{field('Office hours',data.officeHours,v=>edit(d=>d.officeHours=v))}</div></div>}
 {tab==='Courses'&&data.courses.map((c,i)=><div className="admin-panel" key={c.id}><h2>{c.title}</h2><div className="admin-fields">{[['fee','Regular fee'],['discountFee','Discounted fee'],['duration','Course duration'],['classes','Number of classes'],['classDuration','Time per class']].map(([key,label])=><div key={key}>{field(label,c[key],v=>edit(d=>d.courses[i][key]=v),{required:true})}</div>)}</div><label>Description<textarea value={c.desc} maxLength={1000} onChange={e=>edit(d=>d.courses[i].desc=e.target.value)}/></label><label>Included features (one per line)<textarea value={c.features.join('\n')} onChange={e=>edit(d=>d.courses[i].features=e.target.value.split('\n'))}/></label><p className="admin-hint">Update any durations mentioned in the description or included features too.</p></div>)}
 {tab==='Club schedules'&&<><p>Weekly sessions • All times are in Bangladesh time (UTC+6). Set a session to Published when its timetable is confirmed.</p>{Object.entries(data.schedules).map(([id,s])=><div className="admin-panel" key={id}><h2>{s.title}</h2><div className="admin-fields"><label>Status<select aria-label="Status" value={s.status} onChange={e=>edit(d=>d.schedules[id].status=e.target.value)}><option value="unannounced">To be announced</option><option value="active">Published</option><option value="paused">Temporarily paused</option></select></label>{field('Days (e.g. Sunday, Tuesday, Thursday)',s.days,v=>edit(d=>d.schedules[id].days=v),{required:s.status==='active'})}{field('Starts at',s.start,v=>edit(d=>d.schedules[id].start=v),{type:'time',required:s.status==='active'})}{field('Ends at',s.end,v=>edit(d=>d.schedules[id].end=v),{type:'time',required:s.status==='active'})}{field('Room / location',s.location,v=>edit(d=>d.schedules[id].location=v))}{field('Notice (holiday, eligibility or booking)',s.note,v=>edit(d=>d.schedules[id].note=v))}</div><a href={`#/facilities/${id}`}>View care page ↗</a></div>)}</>}
 {tab==='Mock & partial'&&<div className="admin-panel"><h2>Practice test details</h2><div className="admin-fields">{[['mockFee','Full mock test fee'],['partialFee','Partial test fee'],['schedule','Available dates / times']].map(([key,label])=><div key={key}>{field(label,data.tests[key],v=>edit(d=>d.tests[key]=v),{required:true})}</div>)}</div></div>}
 <div className="admin-save"><span>{dirty?'You have unpublished changes':'All changes saved'}</span><button type="button" disabled={busy||!dirty} onClick={()=>{setDraft(clone(content));setDirty(false);setMessage('Edits discarded.')}}>Discard edits</button><button className="button button-primary" disabled={busy||!dirty||!online}>{busy?'Publishing…':'Publish changes'}</button></div></form></>}<p className="admin-status" role="status">{message}</p></section>
}
