import Arrow from '../components/ui/Arrow.jsx'
import SectionHeading from '../components/ui/SectionHeading.jsx'
import CtaBand from '../components/ui/CtaBand.jsx'

export default function ExamRegistrationPage({ navigate }) {
  const essentials = [
    ['01','Valid passport','আপনার test type অনুযায়ী valid ID সাথে রাখুন। Submit করার আগে কী কী document লাগবে, registration team-এর সাথে confirm করুন।'],
    ['02','Test type & module','Academic, General Training, UKVI না Life Skills—কোনটা দরকার বুঝে নিন। Confusion থাকলে booking-এর আগেই জিজ্ঞেস করুন।'],
    ['03','Preferred test date','Preparation, application deadline আর seat availability মিলিয়ে test date বেছে নিন।'],
    ['04','Payment method','Registration-এর সময় কোন payment method চলবে আর official test fee কত, confirm করে নিন।'],
  ]
  return <>
    <section className="registration-hero"><div className="container registration-grid"><div><div className="micro-label light-label"><span/>Official registration support</div><h1>Secure your IELTS date with <em>fewer loose ends.</em></h1><p lang="bn">IELTS test type, documents আর registration নিয়ে HEXA’S Majortila-তে পান personal guidance। Clear plan আর পরিচিত computer test environment-এ প্রস্তুত হোন test day-এর জন্য।</p><div className="hero-actions"><button className="button button-white" onClick={()=>navigate('/contact')}>Get registration support <Arrow/></button><a className="button button-ghost-light" href="tel:+8801710764801">Call +880 1710-764801</a></div><div className="registration-proof"><span>Official venue support</span><span>Academic & GT</span><span>UKVI / Life Skills guidance</span></div></div><div className="registration-ticket"><div className="ticket-top"><span>HX-REG</span><b>IELTS</b></div><div className="ticket-center"><small>REGISTRATION SUPPORT</small><strong>READY</strong><span>Majortila • Sylhet</span></div><div className="ticket-bottom"><span>DOCUMENT CHECK</span><span>DATE SUPPORT</span><span>TEST GUIDANCE</span></div></div></div></section>
    <section className="content-section"><div className="container"><SectionHeading label="Registration options" title="Choose the test that matches" accent="your requirement." copy="কেন IELTS দিচ্ছেন, তার ওপর নির্ভর করে কোন test লাগবে। Payment-এর আগে আপনার institution বা visa application-এর requirement confirm করুন।"/><div className="registration-options"><article><span>ACADEMIC / GENERAL TRAINING</span><h3>Standard IELTS</h3><p lang="bn">Study, migration বা যেসব application-এ standard IELTS Academic বা General Training গ্রহণ করা হয়, সেগুলোর জন্য।</p><button onClick={()=>navigate('/contact')}>Ask which module you need <Arrow size={15}/></button></article><article><span>UKVI</span><h3>IELTS for UKVI</h3><p lang="bn">যেসব UK application-এ approved provider-এর Secure English Language Test লাগে, সেগুলোর জন্য।</p><button onClick={()=>navigate('/contact')}>Ask about UKVI <Arrow size={15}/></button></article><article><span>LIFE SKILLS</span><h3>A1 / B1</h3><p lang="bn">নির্দিষ্ট UK family, settlement বা visa requirement-এর জন্য Speaking আর Listening-এর test।</p><button onClick={()=>navigate('/contact')}>Ask about Life Skills <Arrow size={15}/></button></article></div></div></section>
    <section className="paper-section content-section"><div className="container registration-support-grid"><div><SectionHeading label="Why register with Hexa's" title="Support before you click" accent="confirm." copy="Registration-এ ছোট ভুলও ঝামেলা বাড়াতে পারে। আগে document আর test type check করে নিলে process অনেক সহজ হয়।"/><ul className="check-list"><li>Academic নাকি General Training—বেছে নিতে guidance</li><li>UKVI আর Life Skills নিয়ে support</li><li>Registration details check করতে সাহায্য</li><li>HEXA’S-এর পরিচিত local test environment</li></ul></div><div className="support-card"><span>FROM PREP TO TEST DAY</span><h3>A connected student journey.</h3><p lang="bn">Preparation, computer practice আর registration guidance—সব support এক জায়গায় নিয়ে এগিয়ে যান test day-এর দিকে।</p><button className="button button-primary" onClick={()=>navigate('/contact')}>Speak to the registration desk <Arrow/></button></div></div></section>
    <section className="content-section"><div className="container"><SectionHeading label="Registration essentials" title="Prepare these details" accent="before booking." copy="Requirements বদলাতে পারে। তাই payment-এর আগে আপনার IELTS test-এর current official rules confirm করে নিন।"/><div className="essential-grid">{essentials.map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p lang="bn">{copy}</p></article>)}</div></div></section>
    <CtaBand eyebrow="Need help with your booking?" title="Talk to the registration team before you submit." copy="একবার কথা বললেই test type, documents আর next step নিয়ে পরিষ্কার ধারণা পেতে পারেন।" primary="Get registration support" secondary="Explore courses" onPrimary={()=>navigate('/contact')} onSecondary={()=>navigate('/courses')}/>
  </>
}
