import Arrow from '../components/ui/Arrow.jsx'
import SectionHeading from '../components/ui/SectionHeading.jsx'
import CtaBand from '../components/ui/CtaBand.jsx'

export default function ExamRegistrationPage({ navigate }) {
  const essentials = [
    ['01','Valid passport','Bring the valid identification required for the test type you are booking. The registration team can confirm the current document requirements before submission.'],
    ['02','Test type & module','Know whether you need Academic, General Training, UKVI or Life Skills. If you are unsure, ask before booking.'],
    ['03','Preferred test date','Choose a realistic date based on your preparation status, application deadline and seat availability.'],
    ['04','Payment method','Confirm the accepted payment route and the exact official test fee at the time of registration.'],
  ]
  return <>
    <section className="registration-hero"><div className="container registration-grid"><div><div className="micro-label light-label"><span/>Official registration support</div><h1>Secure your IELTS date with <em>fewer loose ends.</em></h1><p>Get personal guidance at HEXA’S Majortila with your IELTS test type, required documents and registration. Move from preparation to test day with a clear plan and a familiar computer test environment.</p><div className="hero-actions"><button className="button button-white" onClick={()=>navigate('/contact')}>Get registration support <Arrow/></button><a className="button button-ghost-light" href="tel:+8801710764801">Call +880 1710-764801</a></div><div className="registration-proof"><span>Official venue support</span><span>Academic & GT</span><span>UKVI / Life Skills guidance</span></div></div><div className="registration-ticket"><div className="ticket-top"><span>HX-REG</span><b>IELTS</b></div><div className="ticket-center"><small>REGISTRATION SUPPORT</small><strong>READY</strong><span>Majortila • Sylhet</span></div><div className="ticket-bottom"><span>DOCUMENT CHECK</span><span>DATE SUPPORT</span><span>TEST GUIDANCE</span></div></div></div></section>
    <section className="content-section"><div className="container"><SectionHeading label="Registration options" title="Choose the test that matches" accent="your requirement." copy="The correct test depends on why you need IELTS. Confirm the requirement from your institution, visa route or application before paying."/><div className="registration-options"><article><span>ACADEMIC / GENERAL TRAINING</span><h3>Standard IELTS</h3><p>For study, migration and other routes that accept standard IELTS Academic or General Training.</p><button onClick={()=>navigate('/contact')}>Ask which module you need <Arrow size={15}/></button></article><article><span>UKVI</span><h3>IELTS for UKVI</h3><p>For UK routes that specifically require a Secure English Language Test from an approved provider.</p><button onClick={()=>navigate('/contact')}>Ask about UKVI <Arrow size={15}/></button></article><article><span>LIFE SKILLS</span><h3>A1 / B1</h3><p>Speaking-and-listening focused tests used for selected UK family, settlement or visa requirements.</p><button onClick={()=>navigate('/contact')}>Ask about Life Skills <Arrow size={15}/></button></article></div></div></section>
    <section className="paper-section content-section"><div className="container registration-support-grid"><div><SectionHeading label="Why register with Hexa's" title="Support before you click" accent="confirm." copy="Registration errors are frustrating because the stakes are high. A quick document and test-type check can make the process more straightforward."/><ul className="check-list"><li>Guidance on Academic vs General Training</li><li>Support for UKVI and Life Skills routes</li><li>Help reviewing registration details</li><li>Familiar local test environment highlighted by Hexa's</li></ul></div><div className="support-card"><span>FROM PREP TO TEST DAY</span><h3>A connected student journey.</h3><p>Prepare, practise on computer, get registration guidance and move toward test day without switching between disconnected support systems.</p><button className="button button-primary" onClick={()=>navigate('/contact')}>Speak to the registration desk <Arrow/></button></div></div></section>
    <section className="content-section"><div className="container"><SectionHeading label="Registration essentials" title="Prepare these details" accent="before booking." copy="Exact requirements can change, so always confirm the current official rules for your chosen IELTS test before submitting payment."/><div className="essential-grid">{essentials.map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <CtaBand eyebrow="Need help with your booking?" title="Talk to the registration team before you submit." copy="A short check can help you confirm your test type, documents and next step." primary="Get registration support" secondary="Explore courses" onPrimary={()=>navigate('/contact')} onSecondary={()=>navigate('/courses')}/>
  </>
}
