import Arrow from '../components/ui/Arrow.jsx'
import SectionHeading from '../components/ui/SectionHeading.jsx'
import CtaBand from '../components/ui/CtaBand.jsx'
import KineticHero from '../components/home/KineticHero.jsx'
import ScrollGallery from '../components/home/ScrollGallery.jsx'
import AnimatedText from '../components/ui/AnimatedText.jsx'
import { courses } from '../data/courses.js'
import { resources, updates } from '../data/homeContent.js'
export default function HomePage({ navigate }) {
  const featured = [courses[0], courses[4], courses[3], courses[1], courses[2], courses[8]]
  const photos = ['venue.webp','classroom-presentation.webp','computer.webp','computer-lab.webp','english-classroom.webp','welcome-class.webp']
  const photoAlts = ['Computer test preparation facilities at HEXA’S','English speaking practice in a HEXA’S classroom','Students practising in the HEXA’S computer lab','Computer workstations at HEXA’S','An English class at HEXA’S','Students attending a HEXA’S class']
  return <>
    <KineticHero navigate={navigate}/>
    <div className="ticker" aria-label="IELTS Academic, Spoken English, IELTS on Computer, Intensive preparation, Student care"><div className="ticker-track" aria-hidden="true">{[0,1].map(n=><div className="ticker-group" key={n}>{['IELTS Academic','Spoken English','IELTS on Computer','Intensive preparation','Student care'].map(t=><span key={t}>{t}<b>✦</b></span>)}</div>)}</div></div>
    <section className="home-courses paper-section"><div className="container">
      <div className="split-heading"><SectionHeading label="02 / FIND YOUR DIRECTION" title="Different goals." accent="One great place to start."/><button className="button button-outline" onClick={() => navigate('/courses')}>All 12 programs <Arrow/></button></div>
      <div className="editorial-courses">{featured.map((course,i)=><article key={course.title} className="editorial-course reveal"><a href="#/courses" className="course-photo" aria-label={`Explore ${course.title}`}><img src={`./images/${photos[i]}`} alt={photoAlts[i]} loading="lazy" width="640" height="440"/><span>{course.accent}</span><span className="circle-arrow"><Arrow/></span></a><div className="editorial-course-body"><div className="course-eyebrow"><span>0{i+1} / {course.group}</span><span>{course.duration}</span></div><h3>{course.title}</h3><p>{course.desc}</p><button onClick={() => navigate('/courses')}>Explore the program <Arrow size={18}/></button></div></article>)}</div>
    </div></section>
    <section className="experience-section" id="campus"><div className="container experience-grid">
      <div className="experience-media reveal" data-parallax><img src="./images/venue2.webp" alt="HEXA’S IELTS on Computer test centre entrance in Majortila" loading="lazy" width="900" height="1100"/><span className="photo-label">YOUR CAMPUS. YOUR NEXT CHAPTER.</span><div className="experience-inset"><img src="./images/venue.webp" alt="Computer workstations inside the IELTS test venue" loading="lazy" width="350" height="240"/></div></div>
      <div className="experience-copy"><SectionHeading label="03 / THE HEXA’S EXPERIENCE" title="Find your rhythm." accent="with an extensive range of top-tier facilities" copy="Great learning happens when the right environment meets the right support. Make progress in class, then make it your own."/>
      <div className="experience-points">{[['01','Space to practise','Build familiarity in computer labs and a real IELTS test environment.','/facilities'],['02','Care that goes further','Work through reading, writing, listening and speaking challenges with focused support.','/facilities/speaking-care'],['03','A voice that’s your own','Keep the conversation going in the AI Speaking Zone and Speakers’ Cafe.','/facilities/ai-speaking-zone']].map(([n,t,p,url])=><a className="reveal" href={`#${url}`} key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div><Arrow/></a>)}</div><button className="button button-primary" onClick={() => navigate('/facilities')}>Discover student care <Arrow/></button></div>
    </div></section>
    <ScrollGallery/>
    <section className="test-section"><div className="container test-banner reveal"><div className="test-media"><img src="./images/venue2.webp" alt="HEXA’S IELTS on Computer test centre entrance in Majortila" loading="lazy" width="900" height="1100"/></div><div><div className="section-label">FROM PREPARATION TO TEST DAY</div><h2><AnimatedText>You’ve put in the work.</AnimatedText><br/><em><AnimatedText>Let’s take the next step.</AnimatedText></em></h2><p>Get personal guidance with your IELTS test type, documents and registration.</p></div><button className="button button-primary" onClick={() => navigate('/exam-registration')}>IELTS registration <Arrow/></button></div></section>
    <section className="resources-section paper-section"><div className="container"><div className="split-heading"><SectionHeading label="05 / KEEP YOUR MOMENTUM" title="Your learning doesn’t" accent="stop at the door." copy="Join our clubs"/><a href="#/facilities" className="link-button">Explore learning support <Arrow/></a></div><div className="resource-grid">{resources.map((r,i)=><a className="resource-card reveal" href={i===0?'#/facilities/reading-care':i===1?'#/facilities/writing-care':'#/facilities'} key={r.title}><div className="resource-top"><span>{r.type} / Learning support</span><Arrow/></div><strong>{r.mark}</strong><h3>{r.title}</h3><p>{r.subtitle}</p></a>)}</div></div></section>
    <section className="batches-section"><div className="container batches-layout"><div><SectionHeading label="06 / YOUR NEXT MOVE" title="Make room for" accent="your ambition." copy="Choose a time that suits you with our morning, afternoon, and evening batches."/><button className="button button-primary" onClick={() => navigate('/contact')}>Find my next batch <Arrow/></button></div><div className="batch-board">{[['Morning','Start the day with purpose.'],['Afternoon','Build a routine that works.'],['Evening','Keep moving after a busy day.']].map(([t,p],i)=><a href="#/contact" className="reveal" key={t}><span>0{i+1}</span><div><h3>{t} batch</h3><p>{p}</p></div><Arrow/></a>)}</div></div></section>
    <section className="updates-section"><div className="container"><div className="split-heading"><SectionHeading label="FROM THE STUDY DESK" title="Good questions." accent="Better preparation."/></div><div className="updates-grid">{updates.map(([date,category,title],i)=><a href="#/contact" className="reveal" key={title}><span className="update-category">{category}</span><h3>{title}</h3><div>Ask our team <Arrow/></div></a>)}</div></div></section>
    <CtaBand eyebrow="THE NEXT CHAPTER IS YOURS" title="Where will your English take you?" copy="Start with a conversation. We’ll help you find your direction." primary="Let’s find out" secondary="Explore courses" onPrimary={() => navigate('/contact')} onSecondary={() => navigate('/courses')}/>
  </>
}
